// Таблица оптимального времени приёма продуктов
// Источник: аюрведические рекомендации (аспект переваривания в желудке и всасывания в тонком кишечнике)
// "С часов" — от какого часа можно употреблять продукт
// "До часов" — до какого часа лучше употреблять продукт

export const FOOD_TABLE = [
  {
    category: 'Молочные продукты',
    icon: '🥛',
    items: [
      { name: 'Молоко',            from: 6,  to: 21 },
      { name: 'Масло сливочное',   from: 7,  to: 19 },
      { name: 'Ряженка',           from: 7,  to: 19 },
      { name: 'Сметана',           from: 8,  to: 19 },
      { name: 'Кефир',             from: 8,  to: 16 },
      { name: 'Чистый йогурт',     from: 9,  to: 16 },
      { name: 'Творог',            from: 9,  to: 18 },
      { name: 'Сыр',               from: 10, to: 19 },
      { name: 'Простокваша',       from: 10, to: 16 },
      { name: 'Гхи (топлёное масло)', from: 6, to: 21 },
      { name: 'Сыр панир', from: 10, to: 17 },
      { name: 'Сливки', from: 9, to: 18 },
      { name: 'Айран', from: 8, to: 17 },
      { name: 'Топлёное молоко', from: 6, to: 21 },
      { name: 'Козье молоко', from: 6, to: 20 },
      { name: 'Ласси', from: 9, to: 16 },
    ],
  },
  {
    category: 'Специи',
    icon: '🌿',
    items: [
      { name: 'Фенхель',               from: 5,  to: 21 },
      { name: 'Бадьян',                from: 5,  to: 17 },
      { name: 'Ваниль',                from: 5,  to: 17 },
      { name: 'Корица',                from: 6,  to: 17 },
      { name: 'Кардамон зелёный',      from: 7,  to: 21 },
      { name: 'Тмин',                  from: 10, to: 18 },
      { name: 'Имбирь',                from: 10, to: 17 },
      { name: 'Кумин',                 from: 10, to: 16 },
      { name: 'Куркума',               from: 10, to: 17 },
      { name: 'Лавровый лист',         from: 10, to: 15 },
      { name: 'Мак чёрный',            from: 10, to: 15 },
      { name: 'Манго (порошок)',        from: 10, to: 17 },
      { name: 'Шамбала (плоды)',        from: 11, to: 14 },
      { name: 'Асафетида',             from: 11, to: 17 },
      { name: 'Гвоздика',              from: 11, to: 18 },
      { name: 'Горчица чёрная',        from: 11, to: 14 },
      { name: 'Горчица жёлтая',        from: 11, to: 14 },
      { name: 'Калиджи',               from: 11, to: 18 },
      { name: 'Кориандр',              from: 11, to: 16 },
      { name: 'Мускатный орех',        from: 11, to: 16 },
      { name: 'Перец душистый',        from: 11, to: 19 },
      { name: 'Перец чёрный',          from: 11, to: 15 },
      { name: 'Перец красный (ср. жг.)',from: 11, to: 14 },
      { name: 'Перец чили',            from: 11, to: 16 },
      { name: 'Перец паприка',         from: 11, to: 14 },
      { name: 'Шафран', from: 6, to: 20 },
      { name: 'Анис', from: 5, to: 18 },
      { name: 'Пажитник (метхи)', from: 11, to: 15 },
      { name: 'Сумах', from: 10, to: 17 },
      { name: 'Гарам масала', from: 10, to: 17 },
      { name: 'Чёрная соль', from: 9, to: 18 },
      { name: 'Карри лист', from: 9, to: 18 },
      { name: 'Розовый перец', from: 10, to: 17 },
      { name: 'Амчур', from: 10, to: 17 },
    ],
  },
  {
    category: 'Фрукты, сухофрукты, ягоды и мёд',
    icon: '🍎',
    items: [
      { name: 'Изюм',            from: 6,  to: 18 },
      { name: 'Крыжовник',       from: 6,  to: 18 },
      { name: 'Мёд',             from: 6,  to: 18 },
      { name: 'Финик',           from: 6,  to: 19 },
      { name: 'Чернослив',       from: 6,  to: 17 },
      { name: 'Абрикос',         from: 7,  to: 16 },
      { name: 'Банан',           from: 7,  to: 20 },
      { name: 'Виноград',        from: 7,  to: 18 },
      { name: 'Курага',          from: 7,  to: 16 },
      { name: 'Персик',          from: 7,  to: 15 },
      { name: 'Слива',           from: 7,  to: 16 },
      { name: 'Смородина чёрная',from: 7,  to: 20 },
      { name: 'Хурма',           from: 7,  to: 19 },
      { name: 'Яблоки',          from: 7,  to: 19 },
      { name: 'Вишня',           from: 8,  to: 16 },
      { name: 'Груша',           from: 8,  to: 19 },
      { name: 'Земляника',       from: 8,  to: 18 },
      { name: 'Малина',          from: 8,  to: 19 },
      { name: 'Облепиха',        from: 8,  to: 18 },
      { name: 'Шиповник',        from: 8,  to: 18 },
      { name: 'Ананас',          from: 9,  to: 15 },
      { name: 'Мандарин',        from: 9,  to: 16 },
      { name: 'Дыня',            from: 9,  to: 16 },
      { name: 'Апельсин',        from: 10, to: 15 },
      { name: 'Боярышник',       from: 10, to: 21 },
      { name: 'Гранат',          from: 10, to: 18 },
      { name: 'Калина',          from: 10, to: 18 },
      { name: 'Клубника',        from: 10, to: 16 },
      { name: 'Арбуз',           from: 11, to: 17 },
      { name: 'Грейпфрут',       from: 11, to: 15 },
      { name: 'Смородина красная',from: 11, to: 16 },
      { name: 'Лимон',           from: 11, to: 16 },
      { name: 'Авокадо', from: 9, to: 17 },
      { name: 'Манго (свежее)', from: 7, to: 18 },
      { name: 'Киви', from: 8, to: 17 },
      { name: 'Папайя', from: 7, to: 17 },
      { name: 'Кокос', from: 9, to: 17 },
      { name: 'Инжир свежий', from: 7, to: 17 },
      { name: 'Айва', from: 9, to: 16 },
      { name: 'Нектарин', from: 7, to: 17 },
      { name: 'Личи', from: 8, to: 17 },
      { name: 'Маракуйя', from: 8, to: 16 },
      { name: 'Фейхоа', from: 9, to: 16 },
      { name: 'Годжи', from: 7, to: 18 },
      { name: 'Клюква', from: 8, to: 16 },
      { name: 'Голубика', from: 7, to: 17 },
      { name: 'Ежевика', from: 7, to: 17 },
      { name: 'Брусника', from: 8, to: 16 },
      { name: 'Инжир сушёный', from: 8, to: 18 },
    ],
  },
  {
    category: 'Растительные масла и зелень',
    icon: '🫙',
    items: [
      { name: 'Масло оливковое',    from: 9,  to: 18 },
      { name: 'Масло подсолнечное', from: 9,  to: 16 },
      { name: 'Масло соевое',       from: 10, to: 16 },
      { name: 'Масло горчичное',    from: 11, to: 15 },
      { name: 'Масло кукурузное',   from: 11, to: 15 },
      { name: 'Петрушка',           from: 11, to: 18 },
      { name: 'Салат',              from: 11, to: 20 },
      { name: 'Укроп',              from: 11, to: 16 },
      { name: 'Масло кокосовое', from: 6, to: 19 },
      { name: 'Масло кунжутное', from: 7, to: 19 },
      { name: 'Масло льняное', from: 7, to: 18 },
      { name: 'Масло миндальное', from: 7, to: 18 },
      { name: 'Масло гхи', from: 6, to: 21 },
      { name: 'Базилик', from: 7, to: 19 },
      { name: 'Кинза', from: 7, to: 19 },
      { name: 'Мята', from: 6, to: 20 },
      { name: 'Руккола', from: 8, to: 18 },
      { name: 'Шпинат (зелень)', from: 9, to: 17 },
      { name: 'Шалфей', from: 7, to: 18 },
      { name: 'Розмарин', from: 7, to: 18 },
      { name: 'Тимьян', from: 7, to: 18 },
      { name: 'Сельдерей (зелень)', from: 8, to: 18 },
    ],
  },
  {
    category: 'Орехи и семена',
    icon: '🥜',
    items: [
      { name: 'Орех грецкий',         from: 7,  to: 20 },
      { name: 'Семена подсолнечника', from: 9,  to: 17 },
      { name: 'Орех арахис',          from: 9,  to: 18 },
      { name: 'Орех фундук',          from: 10, to: 17 },
      { name: 'Семена тыквы',         from: 11, to: 16 },
      { name: 'Миндаль', from: 8, to: 17 },
      { name: 'Кешью', from: 10, to: 16 },
      { name: 'Кедровый орех', from: 10, to: 16 },
      { name: 'Фисташки', from: 10, to: 16 },
      { name: 'Бразильский орех', from: 10, to: 16 },
      { name: 'Макадамия', from: 10, to: 16 },
      { name: 'Пекан', from: 10, to: 16 },
      { name: 'Семена льна', from: 7, to: 18 },
      { name: 'Семена чиа', from: 7, to: 18 },
      { name: 'Семена кунжута', from: 8, to: 18 },
      { name: 'Семена конопли', from: 8, to: 18 },
    ],
  },
  {
    category: 'Овощи, бахчевые и зелень',
    icon: '🥦',
    items: [
      { name: 'Морковь',              from: 9,  to: 19 },
      { name: 'Патиссон',             from: 9,  to: 20 },
      { name: 'Кабачок',              from: 10, to: 20 },
      { name: 'Огурец',               from: 10, to: 18 },
      { name: 'Свекла',               from: 10, to: 19 },
      { name: 'Тыква',                from: 10, to: 19 },
      { name: 'Редька зелёная',       from: 10, to: 17 },
      { name: 'Репа',                 from: 10, to: 17 },
      { name: 'Баклажан',             from: 11, to: 16 },
      { name: 'Болгарский перец',     from: 11, to: 17 },
      { name: 'Капуста белокочанная', from: 11, to: 18 },
      { name: 'Капуста цветная',      from: 11, to: 16 },
      { name: 'Картофель',            from: 11, to: 15 },
      { name: 'Помидор',              from: 11, to: 15 },
      { name: 'Редис',                from: 11, to: 15 },
      { name: 'Редька чёрная',        from: 11, to: 15 },
      { name: 'Брокколи', from: 11, to: 16 },
      { name: 'Спаржа', from: 11, to: 16 },
      { name: 'Сельдерей (корень)', from: 11, to: 15 },
      { name: 'Шпинат', from: 11, to: 16 },
      { name: 'Артишок', from: 11, to: 15 },
      { name: 'Топинамбур', from: 11, to: 15 },
      { name: 'Батат', from: 11, to: 15 },
      { name: 'Чеснок', from: 10, to: 16 },
      { name: 'Лук репчатый', from: 11, to: 16 },
      { name: 'Лук зелёный', from: 9, to: 17 },
      { name: 'Брюссельская капуста', from: 11, to: 15 },
      { name: 'Кольраби', from: 11, to: 15 },
      { name: 'Бамия (окра)', from: 11, to: 16 },
      { name: 'Зелёный горошек', from: 11, to: 15 },
      { name: 'Цукини', from: 11, to: 16 },
    ],
  },
  {
    category: 'Крупы и бобовые',
    icon: '🌾',
    items: [
      { name: 'Гречневая крупа', from: 8,  to: 20 },
      { name: 'Горох',           from: 11, to: 14 },
      { name: 'Фасоль',          from: 11, to: 14 },
      { name: 'Кукурузная крупа',from: 11, to: 14 },
      { name: 'Овсяная крупа',   from: 11, to: 14 },
      { name: 'Перловая крупа',  from: 11, to: 14 },
      { name: 'Пшеничная крупа', from: 11, to: 14 },
      { name: 'Манная крупа',    from: 11, to: 14 },
      { name: 'Пшено',           from: 11, to: 14 },
      { name: 'Рис',             from: 11, to: 14 },
      { name: 'Соя',             from: 11, to: 14 },
      { name: 'Киноа', from: 10, to: 15 },
      { name: 'Амарант', from: 10, to: 15 },
      { name: 'Булгур', from: 11, to: 14 },
      { name: 'Чечевица красная', from: 11, to: 15 },
      { name: 'Чечевица зелёная', from: 11, to: 14 },
      { name: 'Маш (мунг дал)', from: 10, to: 15 },
      { name: 'Нут', from: 11, to: 14 },
      { name: 'Полба', from: 11, to: 14 },
      { name: 'Рис басмати', from: 10, to: 15 },
      { name: 'Рис бурый', from: 11, to: 14 },
      { name: 'Кускус', from: 11, to: 14 },
      { name: 'Тур дал', from: 11, to: 14 },
    ],
  },
  {
    category: 'Напитки',
    icon: '🍵',
    items: [
      { name: 'Вода тёплая',           from: 4,  to: 23 },
      { name: 'Имбирный чай',          from: 6,  to: 18 },
      { name: 'CCF-чай',               from: 6,  to: 20 },
      { name: 'Зелёный чай',           from: 6,  to: 16 },
      { name: 'Чёрный чай',            from: 6,  to: 15 },
      { name: 'Травяной чай',          from: 6,  to: 21 },
      { name: 'Молоко с куркумой',     from: 18, to: 22 },
      { name: 'Кокосовая вода',        from: 8,  to: 17 },
      { name: 'Вода с лимоном',        from: 5,  to: 11 },
      { name: 'Вода с мёдом',          from: 6,  to: 11 },
      { name: 'Овощной сок',           from: 9,  to: 16 },
      { name: 'Фруктовый сок',         from: 7,  to: 12 },
    ],
  },
  {
    category: 'Грибы',
    icon: '🍄',
    items: [
      { name: 'Шампиньоны',  from: 11, to: 15 },
      { name: 'Вёшенки',     from: 11, to: 15 },
      { name: 'Белые грибы', from: 11, to: 14 },
      { name: 'Лисички',     from: 11, to: 14 },
    ],
  },
];
